apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kaniko-build
  name: kaniko-build
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--context=git://gitlab.com/Hirshberg/goplay.git",
           "--destination=docker.io/cics89/hirshcorp:latest",
           "--skip-tls-verify"] 
    volumeMounts:
      - name: docker-config
        mountPath: /root/.docker/
#     - name: shared-space
#       mountPath: /workspace
    resources: {}
## If some preconfiguration or build that cannot be achieved in multistage build 
## in a Dockerfile is needed unmark this init container and the workspace volume. 
## Note: some container can't mount volumes on root '/'. use /tmp or /mnt instead.
# initContainers:
# - name: goget
#   image: docker.io/library/golang:1.13.5
#   command: ["git"]
#   args: ["clone","{{ git_repo }}","/tmp/workspace"]
#   volumeMounts:
#     - name: shared-space
#       mountPath: /tmp/workspace
#   resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: docker-config
      secret:
        secretName: dockercred  #kubectl create secret generic dockercred --from-file=~/.docker/config.json
#   - name: shared-space
#     emptyDir: {}
